### ISSUE TITLE
Error when renaming map

### ISSUE THREAD

**Issue by MnTronslien** [jason-green-io/papyri#31]
Note we are using the windows fixes provided by Sabotender
```
Line: 395         oldFilename = mapPngFilenameFormat.format(**currentIds.get(mapId)._asdict()).replace(":", "@"      
```

Gives the following error:

```
D:\Documents\Minecraft\PapyrusServerMap>Python papyri.py --world D:\Documents\Minecraft\BukkitServer\Westerdale_one --type java --output D:\Documents\Minecraft\PapyrusServerMap\Output --copytemplate --debug
2020-12-14 23:08:04,259 Found 158 maps in D:\Documents\Minecraft\BukkitServer\Westerdale_one\data
map_*.dat -> nbt        : 100%|████████████████████████████████████████████████
nbt -> png              :   0%|                                                2020-12-14 23:08:04,413 0 is a new map
nbt -> png              :   0%|
Traceback (most recent call last):
  File "papyri.py", line 698, in <module>
    main()
  File "papyri.py", line 674, in main
    latestMaps = makeMaps(args.world, mapsOutput, serverType=args.type, unlimitedTracking=args.includeunlimitedtracking)
  File "papyri.py", line 395, in makeMaps
    oldFilename = mapPngFilenameFormat.format(**currentIds.get(mapId)._asdict()).replace(":", "@")
AttributeError: 'NoneType' object has no attribute '_asdict'
```

Looks like currentIds.get is failing to find the map, resulting in a "NoneType"

**Comment by greener-dot-ca** [comment]
I've pushed 2.0.3 with a revamp of how files are named, try it out and see if it's fixed.

**Comment by MnTronslien** [comment]
We don't have any issues anymore so going to say this is fixed
