### ISSUE TITLE
Breaks with index out of range error

### ISSUE THREAD

**Issue by k-willowhawk** [jason-green-io/papyri#37]
Running a headless 1.17.1 java edition server on Ubunto 20.04 and when pointing to the world file I get this error:

```
root@willowhawk-server:/var/papyri# python3 papyri.py --world /srv/minecraft/world --type java --output /var/www/html --debug
2021-08-29 14:13:15,319 Found 37 maps in /srv/minecraft/world/data
map_*.dat -> nbt        : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████
nbt -> png              :   3%|███
Traceback (most recent call last):
  File "papyri.py", line 702, in <module>
    main()
  File "papyri.py", line 678, in main
    latestMaps = makeMaps(args.world, mapsOutput, serverType=args.type, unlimitedTracking=args.includeunlimitedtracking)
  File "papyri.py", line 351, in makeMaps
    colorTuples = [allColors[x % 256] for x in mapColors]
  File "papyri.py", line 351, in <listcomp>
    colorTuples = [allColors[x % 256] for x in mapColors]
IndexError: list index out of range
```

**Comment by greener-dot-ca** [comment]
1.17 added a few more colours to the maps. Try 2.0.5 and see if that fixes it.
