### ISSUE TITLE
dzsave

### ISSUE THREAD

**Issue by monkeyworknet** [jason-green-io/papyri#6]
MC 1.13

```

[minecraft@mc5 papyri]$ python3.5 papyri.py --mcdata /home/minecraft/server/world/ --output /home/minecraft/static
2018-07-30 15:04:07,101 Namespace(banners=False, mapstats=False, mcdata='/home/minecraft/server/world/', nostitch=True, output='/home/minecraft/static', overlay=False, poi=False, zoomlevel=6)
2018-07-30 15:04:07,101 Copying template web files
2018-07-30 15:04:07,155 Found 142 maps
2018-07-30 15:04:07,156 Parsing map .dat files
2018-07-30 15:04:07,250 Creating folder for overworld
2018-07-30 15:04:07,254 Creating folder for end
2018-07-30 15:04:07,255 Creating folder for nether
2018-07-30 15:04:07,256 Rendering 3 big maps for overworld
2018-07-30 15:04:07,759 Stitching map at -64, -64 zoom level 2 relative coords (0, 0), (512, 512) in 0_-64_-64
2018-07-30 15:04:07,767 Stitching map at -64, 448 zoom level 2 relative coords (0, 512), (512, 1024) in 0_-64_-64
2018-07-30 15:04:07,775 Stitching map at 448, 448 zoom level 2 relative coords (512, 512), (1024, 1024) in 0_-64_-64
2018-07-30 15:04:07,782 Stitching map at 448, -64 zoom level 2 relative coords (512, 0), (1024, 512) in 0_-64_-64
2018-07-30 15:04:07,788 Stitching map at 448, 704 zoom level 1 relative coords (512, 768), (768, 1024) in 0_-64_-64
2018-07-30 15:04:07,793 Stitching map at 192, 448 zoom level 1 relative coords (256, 512), (512, 768) in 0_-64_-64
2018-07-30 15:04:07,798 Stitching map at 192, 192 zoom level 1 relative coords (256, 256), (512, 512) in 0_-64_-64
2018-07-30 15:04:07,802 Stitching map at 576, 704 zoom level 0 relative coords (640, 768), (768, 896) in 0_-64_-64
2018-07-30 15:04:07,806 Stitching map at 320, 448 zoom level 0 relative coords (384, 512), (512, 640) in 0_-64_-64
2018-07-30 15:04:07,811 Stitching map at 320, 320 zoom level 0 relative coords (384, 384), (512, 512) in 0_-64_-64
2018-07-30 15:04:07,815 Stitching map at 448, 320 zoom level 0 relative coords (512, 384), (640, 512) in 0_-64_-64
2018-07-30 15:04:07,819 Stitching map at 448, -64 zoom level 0 relative coords (512, 0), (640, 128) in 0_-64_-64
2018-07-30 15:04:07,823 Stitching map at 448, 64 zoom level 0 relative coords (512, 128), (640, 256) in 0_-64_-64
2018-07-30 15:04:07,826 Stitching map at 576, 64 zoom level 0 relative coords (640, 128), (768, 256) in 0_-64_-64
2018-07-30 15:04:07,830 Stitching map at 576, -64 zoom level 0 relative coords (640, 0), (768, 128) in 0_-64_-64
2018-07-30 15:04:07,834 Saving PNG for 0_-64_-64
2018-07-30 15:04:17,602 Converting png to deepzoom
Traceback (most recent call last):
  File "papyri.py", line 526, in <module>
    pyvips.Image.new_from_file(outPngFile, access='sequential').dzsave(os.path.join(mapOutputPath, "temp"), suffix=".png")
  File "/usr/lib/python3.5/site-packages/pyvips/vimage.py", line 783, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pyvips/voperation.py", line 132, in call
    op = Operation.new_from_name(operation_name)
  File "/usr/lib/python3.5/site-packages/pyvips/voperation.py", line 60, in new_from_name
    raise Error('no such operation {0}'.format(operation_name))
pyvips.error.Error: no such operation dzsave
  VipsOperation: class "dzsave" not found


```

**Comment by monkeyworknet** [comment]
Requirement already satisfied: pyvips in /usr/lib/python3.5/site-packages (2.1.2)
Requirement already satisfied: cffi>=1.0.0 in /usr/lib64/python3.5/site-packages (from pyvips) (1.11.5)
Requirement already satisfied: pycparser in /usr/lib/python3.5/site-packages (from cffi>=1.0.0->pyvips) (2.18)

**Comment by greener-dot-ca** [comment]
What version libvips do you have installed?

**Comment by monkeyworknet** [comment]
actually found the issue - it was with libvips but because it was compiled from source and I was missing a supporting lib for deepzoom. 

"If you are building vips from source you do need to check the summary at the end of configure carefully. You must have the libgsf-1-dev package for vips_dzsave() to work."
